export const LIST_BOOKING_REQUEST = "@listmovie/LIST_BOOKING_REQUEST";
export const LIST_BOOKING_TICKET = "@listmovie/LIST_BOOKING_TICKET";
export const BOOKING_TICKET_SUCCESS = "@listmovie/BOOKING_TICKET_SUCCESS";