export const LIST_BOOKING_REQUEST = "@listmovie/LIST_BOOKING_REQUEST";
export const LIST_BOOKING_SUCCESS = "@listmovie/LIST_BOOKING_SUCCESS";
export const LIST_BOOKING_FAILED = "@listmovie/LIST_BOOKING_FAILED";