export const DETAIL_MOVIE_CINEMA_REQUEST = "DETAIL_MOVIE_CINEMA_REQUEST";
export const DETAIL_MOVIE_CINEMA_SUCCESS = "DETAIL_MOVIE_CINEMA_SUCCESS";
export const DETAIL_MOVIE_CINEMA_FAILED = "DETAIL_MOVIE_CINEMA_FAILED";